"""
Prompt templates for workflow nodes.
"""

from .documentation import (
    VIRTUAL_SUBFLOW_PROMPT,
    PG_SUMMARY_PROMPT,
    PG_WITH_CHILDREN_PROMPT,
    HIERARCHICAL_SUMMARY_PROMPT,
    HIERARCHICAL_DIAGRAM_PROMPT,
    BUSINESS_LOGIC_EXTRACTION_PROMPT
)

__all__ = [
    'VIRTUAL_SUBFLOW_PROMPT',
    'PG_SUMMARY_PROMPT',
    'PG_WITH_CHILDREN_PROMPT',
    'HIERARCHICAL_SUMMARY_PROMPT',
    'HIERARCHICAL_DIAGRAM_PROMPT',
    'BUSINESS_LOGIC_EXTRACTION_PROMPT'
]

